[package]
name = "mmm"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
iced = { version = "0.12.1", features = ["tokio"] }
mcmpmgr = { path = "../mcmpmgr" }
rfd = "0.14.1"
